# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Viktoria Steiner
email: vsteiner.mmt-b2014@fh-salzburg.ac.at
description: > # this means to ignore newlines until "baseurl:"
 			Static page for CMS class at MMT
baseurl: "/cms" # the subpath of your site, e.g. /blog
url: "naiphyx.github.io" # the base hostname & protocol for your site
twitter_username: nope
github_username:  naiphyx

# Build settings
markdown: kramdown
